---
title: "Course Project 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
#unzip to folder if not already done
if(!file.exists("activity.csv"))
{
  unzip("activity.zip")
}
#Read and format data
repdata<-read.csv("activity.csv",stringsAsFactors = FALSE)
repdata$date<-as.Date(repdata$date)


## What is mean total number of steps taken per day?
#get sum of number of steps for each day, omitting the missing values
totalsteps<-tapply(repdata$steps, repdata$date, sum,na.rm=TRUE)

#plot a histogram for total steps taken each day

hist(totalsteps,xlab = "Total steps taken each day",
     main = "Histogram of total steps taken each day")

meansteps<-round(mean(totalsteps))
mediansteps<-median(totalsteps)

print(paste("Mean: ",meansteps))
print(paste("Median: ",mediansteps))

## What is the average daily activity pattern?
library(dplyr)
avg_steps_intvl<-aggregate(steps~interval,data = repdata,FUN = mean,
                           na.rm=TRUE)
                           
# Plotting the time-series graph for average steps taken per interval across all days

library(ggplot2)

ggplot(data = avg_steps_intvl,aes(x=interval,y=steps))+geom_line()+xlab("5 minute interval")+ylab("Average number of steps taken")+ggtitle("Time series plot for avg steps per interval across all days")
                          
max_avg_steps<-avg_steps_intvl[which.max(avg_steps_intvl$steps),][[1]]
print(paste("Interval with max avg steps: ",max_avg_steps))                          

## Imputing missing values

# Calculating total number of missing values in the data
missing_total<-sum(is.na(repdata))
print(paste("Total missing values: ",missing_total))

# Inputing missing data and creating a new dataframe with no missing values. This is done by replacing each missing value by the average of steps for that interval across all days

repdata_full<-repdata
for (i in 1:nrow(repdata_full)) {
    if(is.na(repdata_full$steps[i])) {
        val <- avg_steps_intvl$steps[which(avg_steps_intvl$interval == repdata_full$interval[i])]
        repdata_full$steps[i] <- val 
    }
}

# Make a histogram for the total number of steps each day
#get sum of number of steps for each day
totalsteps_full<-tapply(repdata_full$steps, repdata_full$date, sum)

#plot a histogram for total steps taken each day

hist(totalsteps_full,xlab = "Total steps taken each day",
     main = "Histogram of total steps taken each day")
     
# Calculating mean and median of total steps taken each day after imputing

meansteps_full<-round(mean(totalsteps_full))
mediansteps_full<-round(median(totalsteps_full))

print(paste("Mean: ",meansteps_full))
print(paste("Median: ",mediansteps_full))

# We note that the mean and median steps HAVE CHANGED after imputing the data. The mean and median of steps have both increased after imputing.

## Are there differences in activity patterns between weekdays and weekends?

# Adding a factor variable to the data, indicating whether it is a weekday or weekend

repdata_full$day<-ifelse(weekdays(as.Date(repdata_full$date))=="Saturday" | weekdays(as.Date(repdata_full$date))=="Sunday","weekend","weekday")

repdata_full$day<-factor(repdata_full$day)

# Making a time-series panel plot for average steps per interval acrosss all days for weekdays and weekends

avg_steps_intvl_day<-aggregate(steps~interval+day,data = repdata_full,FUN = mean)

ggplot(data = avg_steps_intvl_day,aes(interval,steps))+geom_line()+facet_grid(day~.)+xlab("5 minute intervals")+ylab("Average number of steps")+ggtitle("Comparing average steps per interval for weekdays and weekends")



